FROM node:8-alpine

# run before build
# npm run build:universal
# npm run generate:prerender
# npm run test:ssr

WORKDIR /app
# Copy dependency definitions
COPY ./package.json /app
COPY ./server.js /app

# Get all the code needed to run the app
COPY ./dist /app/dist
COPY ./static /app/static
COPY ./dist-server /app/dist-server

# Expose the port the app runs in
EXPOSE 80

# Serve the app
CMD ["npm", "run", "server"]
